# Generated by Django 5.2 on 2025-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
